import Head from 'next/head'
import { Inter } from '@next/font/google'
import { db } from "./api/firebase"
import { useState } from 'react';

const inter = Inter({ subsets: ["latin"] });

type Spot = {
  name: string,
  state: string,
  city: string,
  address1: string,
  address2: string,
  star: number,
  udate: {
    nanoseconds: number,
    seconds: number
  }
}

export default function Home() {
  const [spots, setSpots] = useState(new Array<Spot>(100));
  useState(() => {
    db.collection("spots")
      .orderBy("udate")
      .limit(50)
      .onSnapshot((snapshot) => {
        setSpots(snapshot.docs.map((doc) => doc.data() as Spot));
      });
  });

  const checklog = () => {
    console.log(spots);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-5">
        <div className="col-md-11 text-center">
          <button onClick={checklog}>hoge</button>
          <div>
            {spots.map(spot => (
              <div key={spot.name}>
                <p>{spot.city}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  )
}
